import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import Navigation from '../components/navigation'
import HomepageHero from '../components/homepageHero'

import { getHomePage, getNav } from '../lib/api'
import CardSlider from '../components/cardSlider'

import { motion } from 'framer-motion';
import SliderCta from '../components/SliderCta'
import Button from '../components/button'
import InsightCards from '../components/insightCards'





export default function Home({homepage, nav}) {
  
  const navigationItems = nav.nav.navItemCollection.items;
  return (
    <>
      <Head>
        <title>Oshyn New page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <motion.main initial={{opacity:0}} exit={{opacity:0}} animate={{opacity:1}} >
        <Navigation navItems={navigationItems}></Navigation>
        
        {homepage.page.blocksCollection.items.map((item,index)=>{

          console.log(item.__typename)

          if(item.__typename == "Slider"){
            return(
              <section key={index} className='homepage-hero min-h-screen -mt-40 pt-40 w-full bg-background pb-24' >
                <HomepageHero key={index} slider={item.sliderItemsCollection.items}></HomepageHero>
              </section>
            )
          }

          if(item.__typename == "RelatedServicesSlider"){
            return(
              <section key={index} className='related-services py-20 px-10 w-full'>
                <div className='related-services__inner max-w-7xl mx-auto flex flex-wrap items-center'>
                  <div className=' w-full md:w-2/3 pr-9 order-2 md:order-1'>
                    <CardSlider key={index} cardSlides={item.relatedServicesCollection.items}></CardSlider>
                  </div>
                  <div className=' w-full md:w-1/3 order-1 md:order-2 md:mb-8 mb-8'>
                    <h2 className=' font-sora'>{item.title}</h2>
                    <p>{item.description}</p>
                  </div>
                </div>
                
              </section>
            )
          }
          if(item.__typename == "SliderCta"){
            return(
              <section key={index} className='slider-cta pt-36 px-10 w-full bg-slate-900'>
                <SliderCta slides={item}></SliderCta>
              </section>
            )
          }
          if(item.__typename == 'InsightSlider'){
            console.log(item)
            return(
              <section key={index} className='insight py-20 px-10 w-full'>
                <div className='insight__inner max-w-7xl mx-auto flex flex-wrap items-center'>
                  <div className=' w-full md:w-2/3 pr-9 order-2 md:order-1'>
                    <InsightCards key={index} cardSlides={item.slideCollection.items}></InsightCards>
                  </div>
                  <div className=' w-full md:w-1/3 order-1 md:order-2 md:mb-8 mb-8'>
                    <h2 className=' font-sora'>{item.title}</h2>
                    <p>{item.description}</p>
                    <div className='insight-cta flex flex-wrap mt-7'>
                      {item.ctaCollection.items.map((cta,index)=>{
                        console.log(cta.text)
                        return(
                          <div className='insight-cta__item mb-4 mr-3'>
                            <Button type='primary' key={index} url={cta.url}>{cta.text}</Button>
                          </div>
                          
                        )
                      })}
                    </div>
                  </div>
                </div>
                
              </section>
            )
          }

          // FOR THE CLAENDAR iFRAME
          // <iframe src="https://www2.oshyn.com/meetings/oshyn/consult?embed=true&amp;parentHubspotUtk=7d3947221674e0fa9ba4562c3b9786cc&amp;parentPageUrl=https://www-prodbl-lb.oshyn.com/" width="100%" data-hs-ignore="true" style={{minWidth: '312px', minHeight: '516px', height: '756px', border: 'none'}}></iframe>


        })}

      
      </motion.main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </>
  )
}

export async function getStaticProps({ preview = false }) {
  const homepage = (await getHomePage(preview)) ?? [];
  const nav = (await getNav(preview)) ?? [];
  return {
    props: { preview, homepage, nav },
  }
}