import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import Navigation from '../components/navigation'
import HomepageHero from '../components/homepageHero'

import { getHomePage, getNav } from '../lib/api'
import CardSlider from '../components/cardSlider'

import { motion } from 'framer-motion';
import SliderCta from '../components/SliderCta'





export default function Home({homepage, nav}) {
  
  const navigationItems = nav.nav.navItemCollection.items;
  return (
    <>
      <Head>
        <title>Oshyn New page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <motion.main initial={{opacity:0}} exit={{opacity:0}} animate={{opacity:1}} >
        <Navigation navItems={navigationItems}></Navigation>
        
        {homepage.page.blocksCollection.items.map((item,index)=>{

          console.log(item.__typename)

          if(item.__typename == "Slider"){
            return(
              <section className='homepage-hero min-h-screen -mt-40 pt-40 w-full bg-background pb-24' >
                <HomepageHero key={index} slider={item.sliderItemsCollection.items}></HomepageHero>
              </section>
            )
          }

          if(item.__typename == "RelatedServicesSlider"){
            return(
              <section className='related-services py-20 px-10 w-full'>
                <div className='related-services__inner max-w-7xl mx-auto flex flex-wrap items-center'>
                  <div className=' w-2/3 pr-9'>
                    <CardSlider key={index} cardSlides={item.relatedServicesCollection.items}></CardSlider>
                  </div>
                  <div className='w-1/3'>
                    <h2 className=' font-sora'>{item.title}</h2>
                    <p>{item.description}</p>
                  </div>
                </div>
                
              </section>
            )
          }
          if(item.__typename == "SliderCta"){
            return(
              <section className='slider-cta pt-36 px-10 w-full bg-slate-900'>
                <SliderCta slides={item}></SliderCta>
              </section>
            )
          }


        })}

      
      </motion.main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </>
  )
}

export async function getStaticProps({ preview = false }) {
  const homepage = (await getHomePage(preview)) ?? [];
  const nav = (await getNav(preview)) ?? [];
  return {
    props: { preview, homepage, nav },
  }
}